AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  CreateBadgesFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: serverless/create_badges/
      Handler: app.lambda_handler
      Runtime: python3.6
      Events:
        CreateBadges:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /create_badges
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CreateBadgesApi:
    Description: "API Gateway endpoint URL for Prod stage for Create Badges function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/create_badges/"
  CreateBadgesFunction:
    Description: "Create Badges Lambda Function ARN"
    Value: !GetAtt CreateBadgesFunction.Arn
  CreateBadgesFunctionIamRole:
    Description: "Implicit IAM Role created for Create Badges function"
    Value: !GetAtt CreateBadgesFunctionRole.Arn
